### ISSUE TITLE
Expected ParseError for pure ruby variant

### ISSUE THREAD

**Issue by bjfish** [flori/json#394] opened 2019-12-21 15:08 UTC
Steps to reproduce:
`ruby -rjson/pure -e 'p JSON.parse("{")'`

Expected:
` unexpected token at '{' (JSON::ParserError)`

Actual:
`{}`

**Comment by eregon** [comment] 2019-12-21 20:56
See https://github.com/oracle/truffleruby/issues/1570#issuecomment-568171114 for the original issue (TruffleRuby uses json/pure currently).

So this is an issue of the pure version accepting input that the C-ext does not accept.

**Comment by marcandre** [comment] 2020-06-30 03:55
Duplicate of #314

**Closed** 2020-06-30 13:03 UTC
