### ISSUE TITLE
constant JSON::Parser not defined

### ISSUE THREAD

**Issue by reggieb** [flori/json#288] opened 2016-07-01 13:09 UTC
I think the change of the `parser` method from version 1.8 to 2.0 is causing us problems. We are getting this error in one of our builds:

```
Unexpected output: unable to determine line number or type of error/warning for output:
/home/ubuntu/foo-app/vendor/bundle/ruby/2.3.0/gems/json-2.0.0/lib/json/common.rb:28:in `remove_const': constant JSON::Parser not defined (NameError)
```

The [`parser` method](https://github.com/flori/json/blob/v1.8/lib/json/common.rb) defined in json 1.8 looks like this:

```ruby
    def parser=(parser) # :nodoc:
      @parser = parser
      remove_const :Parser if JSON.const_defined_in?(self, :Parser)
      const_set :Parser, parser
    end
```

The [version in the current master](https://github.com/flori/json/blob/master/lib/json/common.rb) looks like this:

```ruby
    def parser=(parser) # :nodoc:
      @parser = parser
      remove_const :Parser if const_defined?(:Parser, true)
      const_set :Parser, parser
    end
```

I think the former version may be less problematic, as our errors go away when we revert to 1.8.3

The full stack trace looks like this:
```
Unexpected output: unable to determine line number or type of error/warning for output:
/home/ubuntu/foo-app/vendor/bundle/ruby/2.3.0/gems/json-2.0.0/lib/json/common.rb:28:in `remove_const': constant JSON::Parser not defined (NameError)
	from /home/ubuntu/foo-app/vendor/bundle/ruby/2.3.0/gems/json-2.0.0/lib/json/common.rb:28:in `parser='
	from /home/ubuntu/foo-app/vendor/bundle/ruby/2.3.0/gems/json-2.0.0/lib/json/ext.rb:10:in `<module:Ext>'
	from /home/ubuntu/foo-app/vendor/bundle/ruby/2.3.0/gems/json-2.0.0/lib/json/ext.rb:6:in `<module:JSON>'
	from /home/ubuntu/foo-app/vendor/bundle/ruby/2.3.0/gems/json-2.0.0/lib/json/ext.rb:3:in `<top (required)>'
	from /home/ubuntu/foo-app/vendor/bundle/ruby/2.3.0/gems/json-2.0.0/lib/json.rb:59:in `require'
	from /home/ubuntu/foo-app/vendor/bundle/ruby/2.3.0/gems/json-2.0.0/lib/json.rb:59:in `<module:JSON>'
	from /home/ubuntu/foo-app/vendor/bundle/ruby/2.3.0/gems/json-2.0.0/lib/json.rb:55:in `<top (required)>'
	from /home/ubuntu/foo-app/vendor/bundle/ruby/2.3.0/gems/rubocop-0.41.1/lib/rubocop/formatter/json_formatter.rb:4:in `require'
	from /home/ubuntu/foo-app/vendor/bundle/ruby/2.3.0/gems/rubocop-0.41.1/lib/rubocop/formatter/json_formatter.rb:4:in `<top (required)>'
	from /home/ubuntu/foo-app/vendor/bundle/ruby/2.3.0/gems/rubocop-0.41.1/lib/rubocop.rb:401:in `require'
	from /home/ubuntu/foo-app/vendor/bundle/ruby/2.3.0/gems/rubocop-0.41.1/lib/rubocop.rb:401:in `<top (required)>'
	from /home/ubuntu/foo-app/vendor/bundle/ruby/2.3.0/gems/rubocop-0.41.1/bin/rubocop:7:in `require'
	from /home/ubuntu/foo-app/vendor/bundle/ruby/2.3.0/gems/rubocop-0.41.1/bin/rubocop:7:in `<top (required)>'
	from /home/ubuntu/foo-app/vendor/bundle/ruby/2.3.0/bin/rubocop:23:in `load'
	from /home/ubuntu/foo-app/vendor/bundle/ruby/2.3.0/bin/rubocop:23:in `<main>'
```

**Comment by kamaradclimber** [comment] 2016-07-01 13:11
seems like a duplicate of #287

**Comment by reggieb** [comment] 2016-07-01 13:14
Looks like the two of us have found the same problem at the same time! So yes, this is a duplicate.

**Closed** 2016-07-01 13:15 UTC
