### ISSUE TITLE
Incompatibility with Ruby 2.2.0

### ISSUE THREAD

**Issue by dougo** [flori/json#229] opened 2014-12-25 20:19 UTC
I upgraded to Ruby 2.2.0, but now I get errors when I install the JSON gem:
```
bash-3.2$ gem install json
Fetching: json-1.8.1.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    /Users/dorleans/.rbenv/versions/2.2.0/bin/ruby -r ./siteconf20141225-66244-1qaxb2p.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling generator.c
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:47: error: too few arguments provided to function-like macro invocation
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                              ^
/Users/dorleans/.rbenv/versions/2.2.0/include/ruby-2.2.0/ruby/intern.h:793:9: note: macro 'rb_str_new' defined here
#define rb_str_new(str, len) __extension__ (    \
        ^
In file included from generator.c:1:
./../fbuffer/fbuffer.h:175:11: warning: incompatible pointer to integer conversion initializing 'VALUE' (aka 'unsigned long') with an expression of type 'VALUE (const char *, long)' [-Wint-conversion]
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
          ^        ~~~~~~~~~~
1 warning and 1 error generated.
make: *** [generator.o] Error 1

make failed, exit code 2

Gem files will remain installed in /Users/dorleans/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/json-1.8.1 for inspection.
Results logged to /Users/dorleans/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/extensions/x86_64-darwin-13/2.2.0-static/json-1.8.1/gem_make.out
bash-3.2$ ruby --version
ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin13]
bash-3.2$ gem --version
2.4.5
```
I don't see anything about `rb_str_new` in the [Ruby 2.2.0 change log](https://github.com/ruby/ruby/blob/v2_2_0/NEWS), so maybe I just have something wrong with my environment? Any tips would be appreciated.

**Comment by 24X7** [comment] 2015-01-04 21:23
When is a real fix available?

**Comment by anatol** [comment] 2015-01-05 23:35
I have the same issue. Browsing internet I found this file that looks interesting http://fossies.org/linux/misc/ruby-2.2.0.tar.gz/ruby-2.2.0/ext/json/fbuffer/fbuffer.h

They replaced the problematic line with

`VALUE result = rb_str_new(FBUFFER_PTR(fb), FBUFFER_LEN(fb));`

**Comment by anatol** [comment] 2015-01-06 03:53
Indeed, after applying following patch the tests pass on my Linux Arch with ruby 2.2.0 installed

```
diff --git a/ext/json/ext/fbuffer/fbuffer.h b/ext/json/ext/fbuffer/fbuffer.h
index af74187..9524fb1 100644
--- a/ext/json/ext/fbuffer/fbuffer.h
+++ b/ext/json/ext/fbuffer/fbuffer.h
@@ -172,7 +172,7 @@ static FBuffer *fbuffer_dup(FBuffer *fb)
 
 static VALUE fbuffer_to_s(FBuffer *fb)
 {
-    VALUE result = rb_str_new(FBUFFER_PAIR(fb));
+    VALUE result = rb_str_new(FBUFFER_PTR(fb), FBUFFER_LEN(fb));
     fbuffer_free(fb);
     FORCE_UTF8(result);
     return result;
```

**Comment by DouglasAllen** [comment] 2015-01-26 17:29
It's not that I need json-1.7.7.gem
But gem install devcenter requires it.
Let's get them updated for Ruby 2.2.0

**Comment by MaxGabriel** [comment] 2015-02-02 17:18
I think this can be closed with the 1.8.2 release. I just tested and was able to install `json` without any problems on 2.2.0, where previously that machine ran into the `too few arguments` error.

**Comment by flori** [comment] 2015-02-03 13:53
Thank you I am closing this issue.

**Closed by flori** 2015-02-03 13:53 UTC

**Comment by oliverbarnes** [comment] 2015-05-12 17:50
Hello, still getting this with 1.8.2:

```
$ gem update --system
Updating rubygems-update
Successfully installed rubygems-update-2.4.6
dyld: lazy symbol binding failed: Symbol not found: _rb_str_new_static
  Referenced from: /Users/work/.rvm/gems/ruby-2.2.1/gems/json-1.8.2/lib/json/ext/parser.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_str_new_static
  Referenced from: /Users/work/.rvm/gems/ruby-2.2.1/gems/json-1.8.2/lib/json/ext/parser.bundle
  Expected in: flat namespace
```

**Comment by buihdk** [comment] 2015-05-22 07:59
i'm getting the same error as @oliverbarnes with ruby-2.2.1

**Comment by scottspeidel** [comment] 2015-08-20 22:46
I am getting the same error as @oliverbarnes with ruby 2.2.2

➜  cam git:(master) ✗ gem update --system
Updating rubygems-update
Successfully installed rubygems-update-2.4.8
dyld: lazy symbol binding failed: Symbol not found: _rb_str_new_static
  Referenced from: /Users/scottspeidel/.rvm/gems/ruby-2.2.2/gems/json-1.8.2/lib/json/ext/parser.bundle
  Expected in: flat namespace

dyld: Symbol not found: _rb_str_new_static
  Referenced from: /Users/scottspeidel/.rvm/gems/ruby-2.2.2/gems/json-1.8.2/lib/json/ext/parser.bundle
  Expected in: flat namespace

[1]    42854 trace trap  gem update --system

What to do?

**Comment by glenfordwilliams** [comment] 2015-11-04 11:05
having a similiar issue under fedora 23
```
 gem install json -v '1.8.1'
Building native extensions.  This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    /usr/bin/ruby -r ./siteconf20151103-5845-wig39e.rb extconf.rb
creating Makefile

make "DESTDIR=" clean
rm -f 
rm -f generator.so  *.o  *.bak mkmf.log .*.time

make "DESTDIR="
gcc -I. -I/usr/include -I/usr/include/ruby/backward -I/usr/include -I. -DJSON_GENERATOR    -fPIC -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -mtune=generic -fPIC -O3 -Wall -O0 -ggdb -m64 -o generator.o -c generator.c
In file included from /usr/include/stdio.h:27:0,
                 from /usr/include/ruby/defines.h:26,
                 from /usr/include/ruby/ruby.h:29,
                 from /usr/include/ruby.h:33,
                 from ../fbuffer/fbuffer.h:5,
                 from generator.c:1:
/usr/include/features.h:328:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
 #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
    ^
In file included from generator.c:1:0:
../fbuffer/fbuffer.h: In function ‘fbuffer_to_s’:
../fbuffer/fbuffer.h:175:47: error: macro "rb_str_new" requires 2 arguments, but only 1 given
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                                               ^
../fbuffer/fbuffer.h:175:20: warning: initialization makes integer from pointer without a cast [-Wint-conversion]
     VALUE result = rb_str_new(FBUFFER_PAIR(fb));
                    ^
Makefile:238: recipe for target 'generator.o' failed
make: *** [generator.o] Error 1

```

**Comment by jdoss** [comment] 2015-11-13 05:44
@glenfordwilliams I had this issue on my Fedora 23 install. Try version 1.8.3 and make sure that the ```gmp-devel``` package is installed. https://github.com/flori/json/issues/259 helped point me in the right direction.

**Comment by volkanunsal** [comment] 2015-11-19 20:01
Still getting this issue with version 1.8.3. Regression?

**Comment by vraravam** [comment] 2015-11-27 06:04
Also getting this issue with 1.8.3 and OSX (El Capitan) with ruby 2.2.3

**Comment by gavinmcgimpsey** [comment] 2015-11-27 19:13
Also getting this on El Capitan with 2.2.3

```
dyld: Symbol not found: _rb_str_new_static
  Referenced from: /Users/gavin/.rvm/gems/ruby-2.2.3/gems/json-1.8.3/lib/json/ext/parser.bundle
  Expected in: flat namespace

Trace/BPT trap: 5
```

**Comment by rajeshkp** [comment] 2015-12-03 05:12
I had the same issue on 2.2.0, but migrating to json version 1.8.3 resolved this issue.

**Comment by gnerkus** [comment] 2015-12-12 18:16
Also getting this on El Capitan wit 2.2.3

```
Error: dyld: lazy symbol binding failed: Symbol not found: _rb_str_new_static Referenced from: /Users/gnerkus/.rvm/gems/ruby-2.2.3/gems/json-1.8.3/lib/json/ext/parser.bundle Expected in: flat namespace
```

**Comment by khrtz** [comment] 2015-12-21 12:51
```sudo gem install json -v1.8.3

```

**Comment by Tonnkie** [comment] 2015-12-28 13:27
the question may be solved by "bundle update" , my problems is the same with you and i solve it in this way

**Comment by akoranne** [comment] 2015-12-28 20:23
Hi All,
I am running MacOS 10.10. 
I installed Ruby 2.3.0. And after reading this thread, install json v1.8.3> 
And trying to install caldecott and continue to get this error 
./../fbuffer/fbuffer.h:151:47: error: too few arguments provided to function-like macro invocation
    VALUE result = rb_str_new(FBUFFER_PAIR(fb));

I appreciate any help! 
Regards,

**Comment by crd** [comment] 2015-12-30 17:29
For anyone using bundle under OSX who receives errors about json v1.8.1: Run `bundle update` (which increments the version of json available) and try again.

**Comment by 21croissants** [comment] 2016-01-06 14:24
`gem pristine json` fixed the issue on ruby 2.2.3 and "El Capitain"

**Comment by PositiveControl** [comment] 2016-01-06 17:11
Thanks @Tonnkie && @crd.

`bundle update` did the trick.

```
OSX: 10.11.2
Ruby 2.3.0
RubyGems: 2.5.1
Bundler: 1.11.2
```

**Comment by HintikkaKimmo** [comment] 2016-01-13 12:50
So I had this same error with RVM ruby 2.2.3 and JSON 1.8.3. For me simply updating bundler to 1.1.2 fixed the issue but I cannot understand why. I did not even bundle install the project after that.

**Comment by DomT4** [comment] 2017-02-25 16:23
https://github.com/flori/json/issues/229#issuecomment-101364344 seems to be back with Ruby 2.4.0 on macOS Sierra 10.12.4, Bundler 1.14.5. If I switch back to using Ruby 2.0.0p648 _(which is the system default on macOS 10.12.4)_ have no such issue. Maybe I'm barking up the wrong tree since nobody else seems to have added a new comment here, but 🤷‍♂️.

**Comment by umarsheikh** [comment] 2017-03-02 13:35
#229 issue is back with ruby 2.4.

compiling generator.c
In file included from generator.c:1:0:
../fbuffer/fbuffer.h: In function ‘fbuffer_to_s’:
../fbuffer/fbuffer.h:175:47: error: macro "rb_str_new" requires 2 arguments, but only 1 given
../fbuffer/fbuffer.h:175:20: warning: initialization makes integer from pointer without a cast [enabled by default]
generator.c: In function ‘generate_json’:
generator.c:832:25: error: ‘rb_cFixnum’ undeclared (first use in this function)
generator.c:832:25: note: each undeclared identifier is reported only once for each function it appears in
generator.c:834:25: error: ‘rb_cBignum’ undeclared (first use in this function)
generator.c: At top level:

An error occurred while installing json (1.7.7), and Bundler cannot continue.

**Comment by lichtamberg** [comment] 2017-08-20 01:27
Have the same problem with ruby 2.3.4 on OSX Sierra.

**Comment by danman01** [comment] 2017-09-29 16:20
Seems JSON version 1.8.3 does the trick http://fuzzyblog.io/blog/ruby/2016/10/11/what-to-do-when-bundle-install-fails-with-json-1-8-1.html
